[package]
name = "synergy-testnet"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonrpc-http-server = "18.0.0"
libp2p = "0.55.0"
rocksdb = "0.23.0"
serde = "1.0.218"
tokio = { version = "1.43.0", features = ["full"] }
md5 = "0.7.0"


[lib]
name = "synergy_testnet"
path = "src/lib.rs"
