[network]
id = 98765
name = "Synergy Testnet"
p2p_port = 30303
rpc_port = 8545
ws_port = 8546
max_peers = 50
bootnodes = [
  "enode://node1@127.0.0.1:30303",
  "enode://node2@127.0.0.1:30304"
]

[blockchain]
block_time = 5
max_gas_limit = "0x2fefd8"
chain_id = 98765

[storage]
database = "rocksdb"
path = "./data"

[api]
enable_http = true
http_port = 8545
enable_ws = true
ws_port = 8546
enable_grpc = true
grpc_port = 50051
